spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ttvdb
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  liquibase:
    change-log: liquibase/ttv.xml